### ISSUE TITLE
迁移《IT 技术相关播客列表》到当前 Org 下维护

### ISSUE THREAD

**Issue by LinuxSuRen** [tech-podcasts/community#5]
@stevending1st 维护了一个[《IT 技术相关播客列表》](https://github.com/stevending1st/it-technology-podcast)，并有意放到当前 org 中一起维护，这是非常好的一件事情。

如果大家认为可以的话，我们最晚可以在本周完成迁移，也就是说没有人反对的话，**2022年10月18日**之前完成。

再次对 @stevending1st 表示感谢！！！

**Comment by LinuxSuRen** [comment]
See also https://github.com/stevending1st/it-technology-podcast/issues/8

**Comment by stevending1st** [comment]
> @stevending1st 维护了一个[《IT 技术相关播客列表》](https://github.com/stevending1st/it-technology-podcast)，并有意放到当前 org 中一起维护，这是非常好的一件事情。
> 
> 如果大家认为可以的话，我们最晚可以在本周完成迁移，也就是说没有人反对的话，**2022年10月18日**之前完成。
> 
> 再次对 @stevending1st 表示感谢！！！

我还在调整，估计会改成一个网站形式，维护起来会简单一点
采用： https://docusaurus.io/zh-CN/

**Comment by LinuxSuRen** [comment]
赞，可以从维护、查阅两个角度来考虑！

**Comment by LinuxSuRen** [comment]
已经邀请 @stevending1st 加入该 Org 了

**Comment by stevending1st** [comment]
> 已经邀请 @stevending1st 加入该 Org 了，帮忙确认下是否可以直接 transfer owner 到 tech-podcasts 呢

只要有创建权限就可以

**Comment by LinuxSuRen** [comment]
或者，你可以给我 https://github.com/stevending1st/it-technology-podcast 一个 admin 权限，我来操作 transfer

**Comment by stevending1st** [comment]
> 或者，你可以给我 https://github.com/stevending1st/it-technology-podcast 一个 admin 权限，我来操作 transfer

我想在 transfer 之前做一个  release......

**Comment by LinuxSuRen** [comment]
好的，那等你的消息

**Comment by stevending1st** [comment]
> 好的，那等你的消息

感谢

**Comment by LinuxSuRen** [comment]
我有个想法哈，如果说能通过 RSS 解析的方式来获取播客节目的描述的话，大家就只需要收集 RSS 地址即可。而且，通过 RSS 可以获取到更多的信息。

**Comment by stevending1st** [comment]
> 我有个想法哈，如果说能通过 RSS 解析的方式来获取播客节目的描述的话，大家就只需要收集 RSS 地址即可。而且，通过 RSS 可以获取到更多的信息。

https://stevending1st.github.io/it-technology-podcast/ 看下新版效果吧。

仅获取 RSS 很难收集一些重要信息， 如一些客户端的订阅链接。
因此将 RSS 作为一个元数据记录在对应播客的主页。

**Comment by LinuxSuRen** [comment]
嗯，确实是的，把 RSS 当作一个重要的元信息，其他的也可以以字段的形式来补充。效果非常赞，至少大大地超出了我的设想。

**Comment by LinuxSuRen** [comment]
@stevending1st 这个 issue 是不是可以关闭了？另外，我有个想法💡，是不是可以考虑把 https://tech-podcasts.github.io/it-technology-podcast/ 当作技术播客“互助小组”（或者其他名称，这个不是重点）的官网呢？

**Comment by LinuxSuRen** [comment]
考虑到这个迁移过程已经完成，先关闭该 issue，如有任何疑问，欢迎再次讨论。
