### ISSUE TITLE
提议：以 Panel 的形式参加 Dev Together，宣传技术类播客

### ISSUE THREAD

**Issue by LinuxSuRen** [tech-podcasts/community#7]
[Dev Together](https://www.bilibili.com/video/BV1NW4y1e7t9/) 是由思否组织的，针对范 Dev Rel 领域的交流会。有不少技术类播客也是带有技术布道、开源布道的属性，我们可以在这次活动上再次为技术类播客代言，让技术圈儿的朋友们可以通过声音来获得咨询、观点、感悟等。

活动地点：北京丽亭华苑酒店
活动日期：2022 年 12 月 17 日

Panel 通常是有 4～5 嘉宾（包含主持人一名）以问答、对话的形式针对一个（或多个）话题进行探讨、交流，该形式的重要特点是：

* 展示多样性的观点
* 吸引不同嘉宾及主持人带来的观众（听众）
* 话题相对轻松易懂

## 参考主题
* [ ] 文章、视频之外，我们为什么还要做播客

## 议题内容简介
内容输出对于每一位社区运营人员来说，无疑是一种非常重要的资讯、信息传达方式。在中文语境下，已经有大量、成熟的文章、视频形式了，那么，播客这种音频形式又有哪些特点、有哪些优势呢？我们会在这次 Panel 上借助多位嘉宾的观点，让更多国内的运营人全面地了解播客。

## 参考议题
* [ ] 播客在制作成本、收益上与其他形式的区别
* [ ] 相比文字、视频，“声音”到底有什么特殊之处
* [ ] 如何在轻松的内容和富有干货的内容之间找到平衡点
* [ ] 哪类技术内容适合通过播客”说“出来
* [ ] 对于零经验的开源社区，如果才能制作出“一定质量”的播客节目呢
* [ ] 海外播客现状

## 嘉宾、主持人征集
@LinuxSuRen 会作为备选主持人，欢迎对该 Panel 感兴趣的朋友们在下面留言。

征集截止日期：10 月 20 日

## References
* [议题征集文稿](https://mp.weixin.qq.com/s/2gGPOxt6aXJx6i_ieElS4A)
* [报名链接](https://jinshuju.net/f/Q38nby)

**Comment by MikeyWei** [comment]
报名参加。（update议题于10/10/2022）

#### 关于主题：讨论“Why”就足够了
也许每个技术播客的主播都有自己的理由或者说原动力，把“初心” share 出来、让目标用户听到。
#### 参考议题：
- 不建议讨论“How”的一系列问题，例如怎么做大做强、怎么做“好”节目。
- 建议多讨论“What”的问题，例如希望自己的播客做成什么方向或什么样子，希望改进哪些环节之类。
- 目前的议题中，对于最后一条海外播客的现状感觉离我们有点远，不知道其他主播有没有关注更多的。

**Comment by WillemJiang** [comment]
报名参加。

**Comment by wey-gu** [comment]
报名参加。

**Comment by majinghe** [comment]
报名参加。

**Comment by zhufengme** [comment]
只要防疫政策允许，就可以参加，也许可以分享一些播客行业方面的动态、数据，以及给大家一些建议。

**Comment by LinuxSuRen** [comment]
感谢各位的大力支持，那我就按照目前的留言来报名了。考虑到有三位朋友 base 在其他城市，也欢迎对该话题感兴趣的朋友们继续留言。

**Comment by LinuxSuRen** [comment]
议题已提交

**Comment by LinuxSuRen** [comment]
各位，已经收到组委会的肯定回复，以下是回复的邮件内容，请各位提前安排好行程，感谢大家的支持！

![image](https://user-images.githubusercontent.com/1450685/201240435-4ff90cd0-2e67-4fed-9352-48065abba024.png)

**Comment by LinuxSuRen** [comment]
各位，收到主办方的通知，这次活动已经延期。详情请查看

![image](https://user-images.githubusercontent.com/1450685/205532999-da402ad0-7cf3-4ab7-b2b7-e29cf5036177.png)

**Comment by LinuxSuRen** [comment]
再次感谢各位的关注和支持！


![image](https://user-images.githubusercontent.com/1450685/228230099-347f46fd-183a-4ee2-ba64-b01451b8c874.png)
